baseurl = "https://jsgrant.github.io"
title = "ACCESS GRANT'D"
copyright = "Copyright &copy; 2021 - Joshua S. Grant"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3
publishDir = "../jsgrant.github.io"

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Joshua S. Grant"
    github = "jsgrant"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "jsg_dev"
    #instagram = "username"
    #stackoverflow = "username"
    youtube = "" # or channel/channelname
    itch = "jsgrant"
    glimesh = "jsgrant"
    artstation = "jsgrant"
    #devto = "username"
    patreon = "jsgrant"

[params]
    tagline = "Joshua S. Grant's  Personal Blog / Site."
    description = ""
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

# uncomment to enable the Tags link on the main toolbar
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 1

# uncomment to enable the Categories link on the main toolbar
  [[menu.main]]
    identifier = "cats"
    name = "Cats"
    url = "/categories"
    weight = 1


  [[menu.main]]
    identifier = "projs"
    name = "Projs"
    url = "/projects"
    weight = 10

